import Header from "@/components/Header";
import "./globals.css";
import CustomHead from "@/components/CustomHead";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CustomHead />
      <body className="mini-h-screen">
        <Header />
        {children}
      </body>
    </html>
  );
}
